version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Running tests..."
      - python -m unittest discover -s tests
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - calculator.py
    - README.md
    - tests/**/*
  discard-paths: no 