version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Checking environment..."
      - python --version
      - pip --version
      - pwd
      - ls -la
  pre_build:
    commands:
      - echo "Setting up test environment..."
      - pip install -r requirements.txt || echo "No requirements.txt found"
      - chmod +x run_tests.py
  build:
    commands:
      - echo "Running tests..."
      - python run_tests.py
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - calculator.py
    - README.md
    - tests/**/*
    - buildspec.yml
    - run_tests.py
    - conftest.py
  discard-paths: no 